spring: 
 profiles: 
  actice: 
   - dev

---
server:
 port: 7700
 
spring:
 profiles: dev
 application:
  name: micro-config-client

eureka:
 client:
  service-url: 
   defaultZone: http://Eureka7000:7000/eureka/,http://Eureka7001:7001/eureka/,http://Eureka7002:7002/eureka/
 instance:
  instanceId: ${spring.application.name}_${server.port}
  prefer-ip-address: true     #访问路径可以显示IP地址
  leaseRenewalIntervalInSeconds: 5 #租期更新时间间隔（默认30秒）
  leaseExpirationDurationInSeconds: 15 #租期到期时间（默认90秒）
---
server:
 port: 7750
 
spring:
 profiles: test
 application:
  name: micro-config-test

eureka:
 client:
  service-url: 
   defaultZone: http://Eureka7000:7000/eureka/,http://Eureka7001:7001/eureka/,http://Eureka7002:7002/eureka/
 instance:
    instanceId: ${spring.application.name}_${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    leaseRenewalIntervalInSeconds: 5 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 15 #租期到期时间（默认90秒）